osx_image: xcode8.2
language: objective-c

script:
  - open -b com.apple.iphonesimulator
  - set -o pipefail && env NSUnbufferedIO=YES
    xcodebuild test
    -project PaynetEasyTransfer.xcodeproj
    -scheme TransferAPI
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6s" | xcpretty
  - pod lib lint
  - pod lib lint --no-clean --verbose --use-libraries | xcpretty
